//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class autherizationv
    {
        public int roleid { get; set; }
        public string rolename { get; set; }
        public string cancreate { get; set; }
        public string canopen { get; set; }
        public string candelete { get; set; }
        public string canupdate { get; set; }
        public string tname { get; set; }
        public int permesionId { get; set; }
    }
}
