//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class diliverytable
    {
        public int did { get; set; }
        public string dname { get; set; }
        public string tell { get; set; }
        public int createdby { get; set; }
        public string isdeleted { get; set; }
        public Nullable<int> modiefiedby { get; set; }
        public Nullable<System.DateTime> lastmodified { get; set; }
    }
}
