//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodtable
    {
        public int fid { get; set; }
        public int catid { get; set; }
        public string fname { get; set; }
        public string fprice { get; set; }
        public byte[] fpic { get; set; }
        public int createdby { get; set; }
        public string isdeleted { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> lastmodiefied { get; set; }
    }
}
