//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fastfoodEntities : DbContext
    {
        public fastfoodEntities()
            : base("name=fastfoodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tablename> tablenames { get; set; }
        public virtual DbSet<usertable> usertables { get; set; }
        public virtual DbSet<rolestable> rolestables { get; set; }
        public virtual DbSet<permesiontable> permesiontables { get; set; }
        public virtual DbSet<permession> permessions { get; set; }
        public virtual DbSet<vuser> vusers { get; set; }
        public virtual DbSet<autherizationv> autherizationvs { get; set; }
        public virtual DbSet<categorytable> categorytables { get; set; }
        public virtual DbSet<foodtable> foodtables { get; set; }
        public virtual DbSet<expensetable> expensetables { get; set; }
        public virtual DbSet<saletable> saletables { get; set; }
        public virtual DbSet<diliverytable> diliverytables { get; set; }
        public virtual DbSet<vorder> vorders { get; set; }
        public virtual DbSet<notetable> notetables { get; set; }
        public virtual DbSet<wasltable> wasltables { get; set; }
        public virtual DbSet<vexpense> vexpenses { get; set; }
    }
}
