//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class permession
    {
        public int permesionId { get; set; }
        public int roleid { get; set; }
        public string ڕۆل { get; set; }
        public string زانیاری { get; set; }
        public string کردنەوە { get; set; }
        public string زیادکردن { get; set; }
        public string گۆڕانکاری { get; set; }
        public string سڕینەوە { get; set; }
    }
}
