//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolestable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rolestable()
        {
            this.isdeleted = "n";
        }
    
        public int roleid { get; set; }
        public string rolename { get; set; }
        public string activated { get; set; }
        public string isdeleted { get; set; }
    }
}
