//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class vexpense
    {
        public decimal eid { get; set; }
        public string ename { get; set; }
        public decimal eprice { get; set; }
        public System.DateTime edate { get; set; }
        public string fullname { get; set; }
        public string isdeleted { get; set; }
    }
}
