//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class vorder
    {
        public decimal sid { get; set; }
        public string fname { get; set; }
        public byte[] fpic { get; set; }
        public decimal sprice { get; set; }
        public int qty { get; set; }
        public string note { get; set; }
        public System.DateTime sdate { get; set; }
        public int createdby { get; set; }
        public decimal wasl { get; set; }
        public string isdeleted { get; set; }
    }
}
