//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fastfoodnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuser
    {
        public int userid { get; set; }
        public string ناوی_سیانی { get; set; }
        public string ڕۆڵ { get; set; }
        public string ناوی_بەکارهێنەر { get; set; }
        public string وشەی_نهێنی { get; set; }
    }
}
